language: node_js
node_js:
  - '10'

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --project campfire-640d7 --token $FIREBASE_TOKEN
